# Generated by Django 6.0.4 on 2026-07-25 03:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rxocrpl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelerClassification',
            fields=[
                ('labeler', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='classification', serialize=False, to='rxocrpl.labeler')),
                ('determination', models.CharField(choices=[('clinical', 'Clinical'), ('otc_cosmetic', 'OTC / Cosmetic'), ('mixed', 'Mixed'), ('indeterminate', 'Indeterminate')], db_index=True, editable=False, max_length=16)),
                ('confidence', models.FloatField(editable=False)),
                ('rx_share', models.FloatField(blank=True, editable=False, null=True)),
                ('n_products', models.PositiveIntegerField(editable=False)),
                ('rx_count', models.PositiveIntegerField(editable=False)),
                ('otc_count', models.PositiveIntegerField(editable=False)),
                ('unknown_count', models.PositiveIntegerField(editable=False)),
                ('rx_fraction', models.FloatField(editable=False)),
                ('otc_fraction', models.FloatField(editable=False)),
                ('unknown_fraction', models.FloatField(editable=False)),
                ('rx_examples', models.JSONField(default=list, editable=False)),
                ('otc_examples', models.JSONField(default=list, editable=False)),
                ('unknown_examples', models.JSONField(blank=True, default=list, editable=False)),
                ('classified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('classifier_version', models.CharField(default='v1', editable=False, help_text='Tag for the LabelerClassifier ruleset that produced this row.', max_length=32)),
            ],
            options={
                'verbose_name': 'labeler classification',
                'verbose_name_plural': 'labeler classifications',
                'indexes': [models.Index(fields=['determination', 'confidence'], name='auxil_label_determi_247d63_idx')],
            },
        ),
    ]
