# Generated by Django 6.0.4 on 2026-07-27 09:13

import computedfields.resolver
import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import rxocrpl.rxgraph.traversal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CspOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reference_image', models.FileField(blank=True, null=True, upload_to='orders/reference/')),
                ('certified_subset', models.BooleanField(default=False)),
                ('scanned_barcodes', models.JSONField(blank=True, default=list)),
                ('expected_components', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'CSP Order',
                'verbose_name_plural': 'CSP Orders',
            },
        ),
        migrations.CreateModel(
            name='Labeler',
            fields=[
                ('labeler_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('verbose_name', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='OCRFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot', models.CharField(blank=True, max_length=100, null=True)),
                ('exp', models.CharField(blank=True, max_length=100, null=True)),
                ('ndc', models.CharField(blank=True, max_length=20, null=True)),
                ('barcode_ndc', models.CharField(blank=True, max_length=20, null=True)),
                ('mfg', models.CharField(blank=True, max_length=100, null=True)),
                ('product', models.CharField(blank=True, max_length=100, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('strength', models.CharField(blank=True, max_length=100, null=True)),
                ('vol_ml', models.CharField(blank=True, max_length=50, null=True)),
                ('mdv', models.CharField(blank=True, max_length=10, null=True)),
                ('instructions', models.CharField(blank=True, max_length=100, null=True)),
                ('lot_confidence', models.FloatField(default=0.0)),
                ('exp_confidence', models.FloatField(default=0.0)),
                ('ndc_confidence', models.FloatField(default=0.0)),
                ('barcode_ndc_confidence', models.FloatField(default=0.0)),
                ('mfg_confidence', models.FloatField(default=0.0)),
                ('product_confidence', models.FloatField(default=0.0)),
                ('brand_confidence', models.FloatField(default=0.0)),
                ('strength_confidence', models.FloatField(default=0.0)),
                ('vol_ml_confidence', models.FloatField(default=0.0)),
                ('mdv_confidence', models.FloatField(default=0.0)),
                ('instructions_confidence', models.FloatField(default=0.0)),
                ('raw_texts', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProductRxNormMapping',
            fields=[
                ('product_ndc', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('rxcui', models.CharField(max_length=20)),
                ('tty', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='RxNormConcept',
            fields=[
                ('rxcui', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('tty', models.CharField(blank=True, choices=[('IN', 'Ingredient'), ('PIN', 'Precise Ingredient'), ('SCDC', 'Semantic Clinical Drug Component'), ('SCD', 'Semantic Clinical Drug'), ('SCDG', 'Semantic Clinical Drug Dose Form Group'), ('BN', 'Branded Name'), ('SBDC', 'Semantic Branded Drug Component'), ('SBD', 'Semantic Branded Drug'), ('BPCK', 'Brand Name Pack'), ('GPCK', 'Generic Pack')], max_length=10, null=True)),
                ('active', models.BooleanField(default=True)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('rxnorm_release', models.CharField(blank=True, max_length=20, null=True)),
                ('rxid', models.PositiveIntegerField(blank=True, editable=False, null=True)),
            ],
            options={
                'verbose_name': 'Concept',
                'verbose_name_plural': 'Concepts',
            },
            bases=(rxocrpl.rxgraph.traversal.RxConceptTraversalMixin, computedfields.resolver._ComputedFieldsModelBase, models.Model),
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('facility_type', models.CharField(blank=True, max_length=100, null=True)),
                ('org', models.CharField(blank=True, help_text='Legacy organization field', max_length=255, null=True)),
                ('admin_id', models.CharField(blank=True, max_length=100, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='rxocrpl.facility')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='rxocrpl.organization')),
            ],
            options={
                'verbose_name_plural': 'Facilities',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_rph', models.BooleanField(default=False)),
                ('user_type', models.CharField(blank=True, max_length=100, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='rxocrpl.facility')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_ndc', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('generic_name', models.CharField(max_length=400)),
                ('brand_name', models.CharField(blank=True, max_length=100, null=True)),
                ('labeler_name', models.CharField(max_length=100)),
                ('dosage_form', models.CharField(max_length=100)),
                ('route', models.JSONField(default=list)),
                ('active_ingredients', models.JSONField(default=list)),
                ('ingredient_count', models.PositiveIntegerField(default=0, editable=False)),
                ('possible_brands', models.CharField(blank=True, default='', editable=False, max_length=400)),
                ('rxcui_mapping', models.JSONField(default=dict)),
                ('active', models.BooleanField(default=True)),
                ('labeler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rxocrpl.labeler')),
                ('concepts', models.ManyToManyField(related_name='products', to='rxocrpl.rxnormconcept')),
            ],
            options={
                'abstract': False,
            },
            bases=(computedfields.resolver._ComputedFieldsModelBase, models.Model),
        ),
        migrations.CreateModel(
            name='PackagedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_code', models.CharField(max_length=2)),
                ('description', models.CharField(max_length=400)),
                ('active', models.BooleanField(default=True)),
                ('package_ndc', models.CharField(editable=False, max_length=13, unique=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packaged_products', to='rxocrpl.product')),
            ],
            options={
                'abstract': False,
            },
            bases=(computedfields.resolver._ComputedFieldsModelBase, models.Model),
        ),
        migrations.CreateModel(
            name='ListedIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('strength', models.CharField(max_length=300)),
                ('unit', models.CharField(max_length=300)),
                ('product', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='rxocrpl.product')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numerator_mag', models.DecimalField(decimal_places=4, max_digits=12)),
                ('numerator_unit', models.CharField(max_length=20)),
                ('denominator_mag', models.DecimalField(decimal_places=4, max_digits=12)),
                ('denominator_unit', models.CharField(max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('lot', models.CharField(blank=True, max_length=100, null=True)),
                ('exp', models.CharField(blank=True, max_length=100, null=True)),
                ('package_ndc', models.CharField(blank=True, max_length=20, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='rxocrpl.csporder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rxocrpl.product')),
            ],
        ),
        migrations.CreateModel(
            name='RoleGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional, for time-boxed elevated access', null=True)),
                ('reason', models.TextField(blank=True, help_text="Optional. Must be 'system_bootstrap' when granted_by is null.")),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rxocrpl.facility')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rxocrpl.organization')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_permissions', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rxocrpl.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_grants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoleGrantEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='rxocrpl.rolegrant')),
            ],
        ),
        migrations.CreateModel(
            name='ProductComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=400)),
                ('active_ingredients', models.JSONField(default=list)),
                ('quantity', models.CharField(blank=True, max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='rxocrpl.product')),
                ('rxnorm_concept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rxocrpl.rxnormconcept')),
            ],
            options={
                'db_table': 'rxocrpl_productcomponent',
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='ApprovedProductReconstitutionScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_ndcs', models.JSONField(default=list)),
                ('whole_product_strength_mag', models.DecimalField(decimal_places=4, max_digits=12)),
                ('whole_product_strength_unit', models.CharField(max_length=20)),
                ('approved_diluents', models.JSONField(default=list)),
                ('diluent_volume_ml', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('final_volume_ml', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rxocrpl.facility')),
                ('concept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rxocrpl.rxnormconcept')),
            ],
        ),
        migrations.CreateModel(
            name='RxNormConceptRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rela', models.CharField(max_length=50)),
                ('numerator_value', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('numerator_unit', models.CharField(blank=True, max_length=20, null=True)),
                ('denominator_value', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('denominator_unit', models.CharField(blank=True, max_length=20, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_relations', to='rxocrpl.rxnormconcept')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_relations', to='rxocrpl.rxnormconcept')),
            ],
            options={
                'verbose_name': 'Concept Relation',
                'verbose_name_plural': 'Concept Relations',
            },
        ),
        migrations.CreateModel(
            name='VerificationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='orders/verification/')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_images', to='rxocrpl.csporder')),
            ],
        ),
        migrations.AddConstraint(
            model_name='rolegrant',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('organization__isnull', False), ('facility__isnull', True)), models.Q(('organization__isnull', True), ('facility__isnull', False)), _connector='OR'), name='grant_scope_exclusive_check'),
        ),
        migrations.AlterUniqueTogether(
            name='rxnormconceptrelation',
            unique_together={('source', 'target', 'rela')},
        ),
    ]
