# Generated by Django 4.2.27 on 2026-06-24 00:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import rxocrpl.rxgraph.traversal


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CspOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reference_image', models.FileField(blank=True, null=True, upload_to='orders/reference/')),
                ('certified_subset', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OCRFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot', models.CharField(blank=True, max_length=100, null=True)),
                ('exp', models.CharField(blank=True, max_length=100, null=True)),
                ('ndc', models.CharField(blank=True, max_length=20, null=True)),
                ('barcode_ndc', models.CharField(blank=True, max_length=20, null=True)),
                ('mfg', models.CharField(blank=True, max_length=100, null=True)),
                ('product', models.CharField(blank=True, max_length=100, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('strength', models.CharField(blank=True, max_length=100, null=True)),
                ('vol_ml', models.CharField(blank=True, max_length=50, null=True)),
                ('mdv', models.CharField(blank=True, max_length=10, null=True)),
                ('instructions', models.CharField(blank=True, max_length=100, null=True)),
                ('lot_confidence', models.FloatField(default=0.0)),
                ('exp_confidence', models.FloatField(default=0.0)),
                ('ndc_confidence', models.FloatField(default=0.0)),
                ('barcode_ndc_confidence', models.FloatField(default=0.0)),
                ('mfg_confidence', models.FloatField(default=0.0)),
                ('product_confidence', models.FloatField(default=0.0)),
                ('brand_confidence', models.FloatField(default=0.0)),
                ('strength_confidence', models.FloatField(default=0.0)),
                ('vol_ml_confidence', models.FloatField(default=0.0)),
                ('mdv_confidence', models.FloatField(default=0.0)),
                ('instructions_confidence', models.FloatField(default=0.0)),
                ('raw_texts', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_ndc', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('generic_name', models.CharField(max_length=100)),
                ('brand_name', models.CharField(blank=True, max_length=100, null=True)),
                ('labeler_name', models.CharField(max_length=100)),
                ('dosage_form', models.CharField(max_length=100)),
                ('route', models.JSONField(default=list)),
                ('active_ingredients', models.JSONField(default=list)),
                ('rxcui_mapping', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='RxNormConcept',
            fields=[
                ('rxcui', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('tty', models.CharField(choices=[('IN', 'Ingredient'), ('PIN', 'Precise Ingredient'), ('SCDC', 'Semantic Clinical Drug Component'), ('SCD', 'Semantic Clinical Drug'), ('SCDG', 'Semantic Clinical Drug Dose Form Group'), ('BN', 'Branded Name'), ('SBDC', 'Semantic Branded Drug Component'), ('SBD', 'Semantic Branded Drug')], max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('rxnorm_release', models.CharField(blank=True, max_length=20, null=True)),
            ],
            bases=(models.Model, rxocrpl.rxgraph.traversal.RxConceptTraversalMixin),
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numerator_mag', models.DecimalField(decimal_places=4, max_digits=12)),
                ('numerator_unit', models.CharField(max_length=20)),
                ('denominator_mag', models.DecimalField(decimal_places=4, max_digits=12)),
                ('denominator_unit', models.CharField(max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('lot', models.CharField(blank=True, max_length=100, null=True)),
                ('exp', models.CharField(blank=True, max_length=100, null=True)),
                ('package_ndc', models.CharField(blank=True, max_length=20, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='rxocrpl.csporder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rxocrpl.product')),
            ],
        ),
        migrations.CreateModel(
            name='RxNormConceptRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rela', models.CharField(max_length=50)),
                ('numerator_value', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('numerator_unit', models.CharField(blank=True, max_length=20, null=True)),
                ('denominator_value', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('denominator_unit', models.CharField(blank=True, max_length=20, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_relations', to='rxocrpl.rxnormconcept')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_relations', to='rxocrpl.rxnormconcept')),
            ],
            options={
                'unique_together': {('source', 'target', 'rela')},
            },
        ),
    ]
