# Generated by Django 6.0.4 on 2026-07-12 08:48

import computedfields.resolver
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rxocrpl', '0002_alter_component_id_alter_ocrfields_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalDrug',
            fields=[
                ('concept', models.ForeignKey(limit_choices_to={'tty': ['SCD', 'SBD']}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='rxocrpl.rxnormconcept')),
                ('route', models.CharField(choices=[('oral', 'Oral'), ('oral_disintegrating', 'Oral Disintegrating'), ('oral_sublingual', 'Oral Sublingual'), ('oral_liquid', 'Oral Liquid'), ('oral_liquid_syrup', 'Oral Liquid Syrup'), ('intravenous', 'Intravenous'), ('intramuscular', 'Intramuscular'), ('subcutaneous', 'Subcutaneous'), ('topical', 'Topical'), ('inhalation', 'Inhalation'), ('rectal', 'Rectal'), ('vaginal', 'Vaginal'), ('intravesicular', 'Intravesicular'), ('nasal', 'Nasal'), ('ophthalmic', 'Ophthalmic'), ('otic', 'Otic')], editable=False, max_length=20)),
                ('quantified', models.BooleanField(default=False, editable=False)),
            ],
            options={
                'abstract': False,
            },
            bases=(computedfields.resolver._ComputedFieldsModelBase, models.Model),
        ),
    ]
