# Generated by Django 6.0.4 on 2026-07-12 09:59

import computedfields.resolver
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rxocrpl', '0003_clinicaldrug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListedIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('strength', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='products', to='rxocrpl.listedingredient'),
        ),
        migrations.CreateModel(
            name='PackagedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_code', models.CharField(max_length=2)),
                ('description', models.CharField(max_length=255)),
                ('package_ndc', models.CharField(editable=False, max_length=13, unique=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packaged_products', to='rxocrpl.product')),
            ],
            options={
                'abstract': False,
            },
            bases=(computedfields.resolver._ComputedFieldsModelBase, models.Model),
        ),
    ]
