# Generated by Django 6.0.4 on 2026-07-12 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rxocrpl', '0004_listedingredient_product_ingredients_packagedproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ingredients',
        ),
    ]
