# Generated by Django 6.0.4 on 2026-07-12 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rxocrpl', '0005_remove_product_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='listedingredient',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='rxocrpl.product'),
            preserve_default=False,
        ),
    ]
