# Generated by Django 6.0.4 on 2026-07-12 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rxocrpl', '0006_listedingredient_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Labeler',
            fields=[
                ('labeler_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('verbose_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='labeler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rxocrpl.labeler'),
        ),
    ]
