# Generated by Django 6.0.2 on 2026-07-13 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rxocrpl', '0007_labeler_product_labeler'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('org', models.CharField(blank=True, max_length=255, null=True)),
                ('facility_type', models.CharField(blank=True, max_length=100, null=True)),
                ('admin_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Facilities',
            },
        ),
        migrations.CreateModel(
            name='ProductRxNormMapping',
            fields=[
                ('product_ndc', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('rxcui', models.CharField(max_length=20)),
                ('tty', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='listedingredient',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='listedingredient',
            name='product',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='rxocrpl.product'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user_type', models.CharField(blank=True, max_length=100, null=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='rxocrpl.facility')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovedProductReconstitutionScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_ndcs', models.JSONField(default=list)),
                ('whole_product_strength_mag', models.DecimalField(decimal_places=4, max_digits=12)),
                ('whole_product_strength_unit', models.CharField(max_length=20)),
                ('approved_diluents', models.JSONField(default=list)),
                ('diluent_volume_ml', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('final_volume_ml', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rxocrpl.facility')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rxocrpl.user')),
            ],
        ),
    ]
