# Generated by Django 6.0.2 on 2026-07-13 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rxocrpl', '0008_facility_productrxnormmapping_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='csporder',
            name='expected_components',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='csporder',
            name='scanned_barcodes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='VerificationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='orders/verification/')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_images', to='rxocrpl.csporder')),
            ],
        ),
    ]
