# Generated by Django 6.0.2 on 2026-07-13 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rxocrpl', '0009_csporder_expected_components_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrxnormmapping',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productrxnormmapping',
            name='tty',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='rxnormconcept',
            name='tty',
            field=models.CharField(blank=True, choices=[('IN', 'Ingredient'), ('PIN', 'Precise Ingredient'), ('SCDC', 'Semantic Clinical Drug Component'), ('SCD', 'Semantic Clinical Drug'), ('SCDG', 'Semantic Clinical Drug Dose Form Group'), ('BN', 'Branded Name'), ('SBDC', 'Semantic Branded Drug Component'), ('SBD', 'Semantic Branded Drug')], max_length=10, null=True),
        ),
    ]
