# Generated by Django 6.0.4 on 2026-07-14 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rxocrpl', '0010_alter_productrxnormmapping_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ingredient_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
