# Generated by Django 6.0.4 on 2026-07-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rxocrpl', '0012_organization_role_facility_parent_alter_facility_org_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagedproduct',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
