# Generated by Django 6.0.4 on 2026-07-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rxocrpl', '0013_packagedproduct_active_product_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='labeler',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
