# Generated by Django 6.0.4 on 2026-07-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rxocrpl', '0014_labeler_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listedingredient',
            name='name',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='listedingredient',
            name='strength',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='listedingredient',
            name='unit',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='packagedproduct',
            name='description',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='product',
            name='generic_name',
            field=models.CharField(max_length=400),
        ),
    ]
