# Generated by Django 6.0.4 on 2026-07-17 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rxocrpl', '0015_alter_listedingredient_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listedingredient',
            name='unit',
            field=models.CharField(max_length=300),
        ),
    ]
