# Generated by Django 6.0.4 on 2026-07-22 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rxocrpl', '0017_user_auth_user_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='csporder',
            options={'verbose_name': 'CSP Order', 'verbose_name_plural': 'CSP Orders'},
        ),
        migrations.AddField(
            model_name='product',
            name='concepts',
            field=models.ManyToManyField(related_name='products', to='rxocrpl.rxnormconcept'),
        ),
    ]
