# Generated by Django 6.0.4 on 2026-07-22 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rxocrpl', '0018_alter_csporder_options_product_concepts'),
    ]

    operations = [
        migrations.AddField(
            model_name='rxnormconcept',
            name='rxid',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
