# Generated by Django 6.0.4 on 2026-06-24 04:53

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('path', models.CharField(max_length=1024)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Canonical Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_rph', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ComponentLibraryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=10)),
                ('data', models.JSONField(default=dict)),
                ('verifier', models.ForeignKey(blank=True, limit_choices_to={'is_rph': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_library_entries', to=settings.AUTH_USER_MODEL)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_entries', to='cv.manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='CompoundedSterileProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prepared_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('preparer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_compounds', to=settings.AUTH_USER_MODEL)),
                ('verifier', models.ForeignKey(limit_choices_to={'is_rph': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compounds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComponentInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lot_number', models.CharField(blank=True, max_length=64)),
                ('expiration', models.DateField(blank=True, null=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='cv.componentlibraryentry')),
                ('compound', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='components', to='cv.compoundedsterileproduct')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImageSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('box', models.JSONField(default=dict)),
                ('polygon', models.JSONField(blank=True, default=list)),
                ('kind', models.CharField(choices=[('instance', 'Instance'), ('stuff', 'Stuff'), ('watershed_basin', 'Watershed basin')], default='instance', max_length=24)),
                ('class_label', models.CharField(blank=True, max_length=128)),
                ('instance_id', models.PositiveIntegerField(blank=True, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('area_px', models.PositiveIntegerField(blank=True, null=True)),
                ('centroid', models.JSONField(blank=True, default=dict)),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='segments', to='cv.componentinstance')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='cv.image')),
            ],
        ),
        migrations.CreateModel(
            name='ImageSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('captured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captured_image_sets', to=settings.AUTH_USER_MODEL)),
                ('compound', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_set', to='cv.compoundedsterileproduct')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='image',
            name='image_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cv.imageset'),
        ),
        migrations.CreateModel(
            name='LabelerCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=5)),
                ('verifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_labeler_codes', to=settings.AUTH_USER_MODEL)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labeler_codes', to='cv.manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='ManufacturerAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='cv.manufacturer')),
                ('verifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_aliases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PipelineRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('algorithm', models.CharField(choices=[('panoptic', 'Panoptic'), ('watershed', 'Watershed')], max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('model_name', models.CharField(blank=True, max_length=128)),
                ('model_version', models.CharField(blank=True, max_length=128)),
                ('code_ref', models.CharField(blank=True, help_text='Git SHA or release tag', max_length=64)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('image_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_runs', to='cv.imageset')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipeline_runs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OcrToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.TextField()),
                ('confidence', models.DecimalField(decimal_places=3, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('role', models.IntegerField(choices=[(1, 'Text'), (2, 'Component name'), (3, 'Manufacturer'), (4, 'Strength'), (5, 'Route'), (6, 'Expiration'), (7, 'Lot number'), (8, 'NDC'), (9, 'Package')], default=1)),
                ('role_confidence', models.DecimalField(decimal_places=3, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('bbox', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='cv.imagesegment')),
                ('source_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocr_tokens', to='cv.pipelinerun')),
            ],
        ),
        migrations.CreateModel(
            name='SegmentationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label_map_path', models.CharField(blank=True, max_length=1024)),
                ('edge_mask_path', models.CharField(blank=True, max_length=1024)),
                ('panoptic_map_path', models.CharField(blank=True, max_length=1024)),
                ('marker_map_path', models.CharField(blank=True, max_length=1024)),
                ('num_regions', models.PositiveIntegerField(default=0)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segmentation_results', to='cv.image')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='cv.pipelinerun')),
            ],
        ),
        migrations.AddField(
            model_name='imagesegment',
            name='result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='segments', to='cv.segmentationresult'),
        ),
        migrations.AddConstraint(
            model_name='image',
            constraint=models.UniqueConstraint(fields=('image_set', 'path'), name='unique_imageset_path'),
        ),
        migrations.AddConstraint(
            model_name='labelercode',
            constraint=models.UniqueConstraint(fields=('manufacturer', 'code'), name='unique_mfr_labeler_code'),
        ),
        migrations.AddConstraint(
            model_name='labelercode',
            constraint=models.CheckConstraint(condition=models.Q(('code__regex', '^\\d{4,5}$')), name='labeler_code_format'),
        ),
        migrations.AddConstraint(
            model_name='componentlibraryentry',
            constraint=models.UniqueConstraint(fields=('manufacturer', 'code'), name='unique_mfr_code'),
        ),
        migrations.AddIndex(
            model_name='pipelinerun',
            index=models.Index(fields=['image_set', 'algorithm', 'started_at'], name='cv_pipeline_image_s_bcab28_idx'),
        ),
        migrations.AddIndex(
            model_name='pipelinerun',
            index=models.Index(fields=['status'], name='cv_pipeline_status_a59c97_idx'),
        ),
        migrations.AddConstraint(
            model_name='pipelinerun',
            constraint=models.CheckConstraint(condition=models.Q(('finished_at__isnull', True), ('finished_at__gte', models.F('started_at')), _connector='OR'), name='run_finished_after_started'),
        ),
        migrations.AddIndex(
            model_name='ocrtoken',
            index=models.Index(fields=['segment', 'role'], name='cv_ocrtoken_segment_f580f0_idx'),
        ),
        migrations.AddIndex(
            model_name='ocrtoken',
            index=models.Index(fields=['source_run', 'role'], name='cv_ocrtoken_source__511578_idx'),
        ),
        migrations.AddConstraint(
            model_name='segmentationresult',
            constraint=models.UniqueConstraint(fields=('run', 'image'), name='unique_run_image_result'),
        ),
        migrations.AddIndex(
            model_name='imagesegment',
            index=models.Index(fields=['image', 'kind'], name='cv_imageseg_image_i_f43a8c_idx'),
        ),
        migrations.AddIndex(
            model_name='imagesegment',
            index=models.Index(fields=['result', 'kind'], name='cv_imageseg_result__6102b9_idx'),
        ),
        migrations.AddConstraint(
            model_name='imagesegment',
            constraint=models.UniqueConstraint(condition=models.Q(('instance_id__isnull', False), ('result__isnull', False)), fields=('result', 'instance_id'), name='unique_instance_per_result'),
        ),
    ]
