# Generated by Django 6.0.4 on 2026-07-12 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='labelercode',
            name='labeler_code_format',
        ),
        migrations.RemoveConstraint(
            model_name='pipelinerun',
            name='run_finished_after_started',
        ),
    ]
