# Generated by Django 6.0.2 on 2026-07-15 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_user_facility_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentinstance',
            name='volume_ml',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Volume drawn from this container in mL', max_digits=10, null=True),
        ),
    ]
